import { createHash, randomBytes } from "node:crypto";
import { lstat, mkdir, open, readFile, realpath, rename, rm } from "node:fs/promises";
import { basename, delimiter, dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { MANAGED_MARKERS } from "../../shared/constants";
import type { BuildProfile, DocumentTarget, Engine, StructureNode } from "../../shared/types";
import { isSafeRelativePath } from "./scanner";

export interface ProfileRuntimeResult {
  buildDirectory: string;
  runtimePath: string;
  wrapperPath: string;
  latexmkrcPath: string;
  generatedEntryPath: string;
  originalEntryPath: string;
  renderedStructure: string;
  warnings: string[];
}

export interface ProfileRuntimeOptions {
  focusNodes?: string[];
  engine?: Exclude<Engine, "auto">;
}

export class ProfileRuntimeError extends Error {
  constructor(message: string, public readonly code: "PATH_OUTSIDE_PROJECT" | "ENTRY_INVALID" | "MARKERS_INVALID") {
    super(message);
    this.name = "ProfileRuntimeError";
  }
}

function safeId(value: string): string {
  const sanitized = value.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^[-.]+|[-.]+$/g, "");
  if (sanitized && sanitized === value && value !== "." && value !== "..") return sanitized;
  const digest = createHash("sha256").update(value).digest("hex").slice(0, 10);
  return `${sanitized || "default"}-${digest}`;
}

export function profileBuildDirectoryPath(projectRoot: string, targetId: string, profileId: string): string {
  return join(resolve(projectRoot), ".latex-workbench", "build", safeId(targetId), safeId(profileId));
}

async function resolveInside(root: string, candidate: string): Promise<string> {
  const absoluteRoot = resolve(root);
  const absoluteCandidate = isAbsolute(candidate) ? resolve(candidate) : resolve(absoluteRoot, candidate);
  const relation = relative(absoluteRoot, absoluteCandidate);
  if (relation === "" || (!relation.startsWith(`..${sep}`) && relation !== ".." && !isAbsolute(relation))) {
    const [rootReal, candidateReal] = await Promise.all([realpath(absoluteRoot), realpath(absoluteCandidate)]);
    const realRelation = relative(rootReal, candidateReal);
    if (realRelation === "" || (!realRelation.startsWith(`..${sep}`) && realRelation !== ".." && !isAbsolute(realRelation))) {
      return candidateReal;
    }
  }
  throw new ProfileRuntimeError(`Path escapes the project root: ${candidate}`, "PATH_OUTSIDE_PROJECT");
}

async function ensureBuildDirectory(root: string, targetId: string, profileId: string): Promise<string> {
  const rootReal = await realpath(root);
  let current = rootReal;
  for (const segment of [".latex-workbench", "build", safeId(targetId), safeId(profileId)]) {
    current = join(current, segment);
    try {
      const info = await lstat(current);
      if (info.isSymbolicLink() || !info.isDirectory()) {
        throw new ProfileRuntimeError(`Build path is not a private directory: ${current}`, "PATH_OUTSIDE_PROJECT");
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      await mkdir(current);
    }
    const currentReal = await realpath(current);
    const relation = relative(rootReal, currentReal);
    if (relation.startsWith(`..${sep}`) || relation === ".." || isAbsolute(relation)) {
      throw new ProfileRuntimeError(`Build path escapes the project root: ${current}`, "PATH_OUTSIDE_PROJECT");
    }
    current = currentReal;
  }
  return current;
}

async function writeGeneratedFile(filePath: string, content: string): Promise<void> {
  const temporaryPath = join(dirname(filePath), `.${basename(filePath)}.${process.pid}.${randomBytes(6).toString("hex")}.tmp`);
  let temporaryExists = false;
  try {
    const handle = await open(temporaryPath, "wx", 0o600);
    temporaryExists = true;
    try {
      await handle.writeFile(content, "utf8");
      await handle.sync();
    } finally {
      await handle.close();
    }
    await rename(temporaryPath, filePath);
    temporaryExists = false;
  } finally {
    if (temporaryExists) await rm(temporaryPath, { force: true });
  }
}

function texPath(path: string): string {
  return path.replace(/\\/g, "/").replace(/([%#])/g, "\\$1");
}

function portableSearchPath(path: string): string {
  return path.replace(/\\/g, "/").replace(/'/g, "\\'").replace(/\/$/, "");
}

export function renderLatexmkrc(projectRoot: string, entryDirectory: string, buildDirectory: string): string {
  const roots = [...new Set([entryDirectory, projectRoot, buildDirectory].map((path) => portableSearchPath(path)))];
  const prefix = roots.map((path) => `${path}//${delimiter}`).join("");
  return [
    "# Generated by LaTeX Workbench. Do not edit.",
    "sub lw_prepend_path {",
    "  my ($name, $prefix) = @_;",
    "  my $current = defined $ENV{$name} ? $ENV{$name} : '';",
    "  $ENV{$name} = $prefix . $current;",
    "}",
    `lw_prepend_path('TEXINPUTS', '${prefix}');`,
    `lw_prepend_path('BIBINPUTS', '${prefix}');`,
    `lw_prepend_path('BSTINPUTS', '${prefix}');`,
    ""
  ].join("\n");
}

function escapeTexText(value: string): string {
  return value.replace(/([#$%&_{}])/g, "\\$1").replace(/~/g, "\\textasciitilde{}").replace(/\^/g, "\\textasciicircum{}");
}

function orderedNodes(target: DocumentTarget, profile: BuildProfile): StructureNode[] {
  const byId = new Map(target.structure.map((node) => [node.id, node]));
  const ordered: StructureNode[] = [];
  const seen = new Set<string>();

  for (const id of profile.order) {
    const node = byId.get(id);
    if (node && !seen.has(id)) {
      ordered.push(node);
      seen.add(id);
    }
  }

  for (const node of [...target.structure].sort((left, right) => left.order - right.order)) {
    if (!seen.has(node.id)) ordered.push(node);
  }
  return ordered;
}

function maskComments(source: string): string {
  return source.replace(/(^|[^\\])%[^\r\n]*/gm, (match) => match.replace(/[^\r\n]/g, " "));
}

export function includeAuxiliaryDirectories(source: string, warnings: string[] = []): string[] {
  const directories = new Set<string>();
  const pattern = /\\include\s*\{([^{}]+)\}/g;
  let match: RegExpExecArray | null;
  const masked = maskComments(source);
  while ((match = pattern.exec(masked)) !== null) {
    const requested = match[1].trim();
    if (requested.includes("\\")) {
      warnings.push(`Dynamic \\include path was preserved without an auxiliary directory: ${requested}`);
      continue;
    }
    if (!isSafeRelativePath(requested)) {
      throw new ProfileRuntimeError(`Unsafe \\include path: ${requested}`, "ENTRY_INVALID");
    }
    const directory = dirname(requested.replace(/\//g, sep));
    if (directory !== ".") directories.add(directory);
  }
  return [...directories];
}

async function ensureBuildSubdirectory(buildDirectory: string, relativeDirectory: string): Promise<void> {
  const buildReal = await realpath(buildDirectory);
  let current = buildReal;
  for (const segment of relativeDirectory.split(/[\\/]+/).filter(Boolean)) {
    if (segment === "." || segment === "..") {
      throw new ProfileRuntimeError(`Unsafe include auxiliary directory: ${relativeDirectory}`, "PATH_OUTSIDE_PROJECT");
    }
    current = join(current, segment);
    try {
      const info = await lstat(current);
      if (info.isSymbolicLink() || !info.isDirectory()) {
        throw new ProfileRuntimeError(`Include auxiliary path is not a private directory: ${current}`, "PATH_OUTSIDE_PROJECT");
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      await mkdir(current);
    }
    const currentReal = await realpath(current);
    const relation = relative(buildReal, currentReal);
    if (relation === ".." || relation.startsWith(`..${sep}`) || isAbsolute(relation)) {
      throw new ProfileRuntimeError(`Include auxiliary path escapes the build directory: ${current}`, "PATH_OUTSIDE_PROJECT");
    }
    current = currentReal;
  }
}

function targetWithPreservedInputCommands(
  source: string,
  projectRoot: string,
  entryPath: string,
  target: DocumentTarget
): DocumentTarget {
  const masked = maskComments(source);
  const pattern = /\\(?:input|include|subfile)\s*\{([^{}]+)\}/g;
  const commandsByPath = new Map<string, string[]>();
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(masked)) !== null) {
    const requestedPath = match[1].trim();
    const pathWithExtension = extname(requestedPath) ? requestedPath : `${requestedPath}.tex`;
    const absolute = resolve(dirname(entryPath), pathWithExtension);
    const relation = relative(projectRoot, absolute);
    if (relation === ".." || relation.startsWith(`..${sep}`) || isAbsolute(relation)) continue;
    const key = relation.split(sep).join("/").toLocaleLowerCase("en-US");
    const commands = commandsByPath.get(key) ?? [];
    commands.push(source.slice(match.index, match.index + match[0].length));
    commandsByPath.set(key, commands);
  }

  return {
    ...target,
    structure: target.structure.map((node) => {
      if (!node.path) return node;
      const key = node.path.replace(/\\/g, "/").toLocaleLowerCase("en-US");
      const commands = commandsByPath.get(key);
      const originalCommand = commands?.shift();
      return originalCommand ? { ...node, contentSource: originalCommand } : node;
    })
  };
}

function nodeEnabled(node: StructureNode, profile: BuildProfile): boolean {
  return profile.enabledBlocks[node.id] !== false && profile.enabledBlocks[node.kind] !== false;
}

function sourceForNode(node: StructureNode): string {
  if (node.contentSource?.trim()) {
    const content = node.contentSource.trim();
    const renderedContent = content.startsWith("\\") ? content : `\\input{${texPath(content)}}`;
    return node.titleSource === "main" && node.headingSource?.trim()
      ? `${node.headingSource.trim()}\n${renderedContent}`
      : renderedContent;
  }
  switch (node.kind) {
    case "title": return "\\maketitle";
    case "frontmatter": return "\\frontmatter";
    case "toc": return "\\tableofcontents";
    case "localToc": return "\\localtableofcontents";
    case "listOfFigures": return "\\listoffigures";
    case "listOfTables": return "\\listoftables";
    case "listOfChanges": return "\\listofchanges";
    case "mainmatter": return "\\mainmatter";
    case "part": return node.headingSource?.trim() || `\\part{${escapeTexText(node.title)}}`;
    case "appendix": return node.path ? `\\appendix\n\\input{${texPath(node.path)}}` : "\\appendix";
    case "bibliography": {
      if (!node.path) return "\\printbibliography";
      const bibliographyPath = node.path.replace(/\.bib$/i, "");
      return `\\bibliography{${texPath(bibliographyPath)}}`;
    }
    case "index": return "\\printindex";
    case "backmatter": return "\\backmatter";
    case "cover":
    case "chapter":
    case "input":
    case "raw":
      if (node.path) return `\\input{${texPath(node.path)}}`;
      return node.headingSource?.trim() ?? `% ${node.kind}: ${node.title}`;
  }
}

function titleOnlySource(node: StructureNode): string {
  if (node.headingSource?.trim()) return node.headingSource.trim();
  return `\\chapter{${escapeTexText(node.title)}}`;
}

function renderClassDeclaration(target: DocumentTarget): string {
  const options = Object.entries(target.classConfig.options)
    .filter(([, value]) => value !== false && value !== "")
    .map(([key, value]) => value === true ? key : `${key}=${value}`);
  const fallback = target.classConfig.rawOptions.filter(Boolean);
  const serialized = options.length ? options : fallback;
  return serialized.length
    ? `\\documentclass[${serialized.join(",")}]{${target.classConfig.name}}`
    : `\\documentclass{${target.classConfig.name}}`;
}

function renderManagedPackages(target: DocumentTarget, profile: BuildProfile): { source: string; warnings: string[]; preserve: boolean } {
  const warnings: string[] = [];
  let preserve = false;
  const packages = [...target.packages]
    .filter((item) => item.enabled && item.source !== "class" && profile.enabledBlocks[item.id] !== false && profile.enabledBlocks[item.name] !== false)
    .sort((left, right) => left.order - right.order);
  const lines = ["% Packages managed by LaTeX Workbench."];
  for (const item of packages) {
    if (item.condition) {
      warnings.push(`Conditional package ${item.name} was left in the original source.`);
      preserve = true;
      continue;
    }
    const options = item.options.length ? `[${item.options.join(",")}]` : "";
    lines.push(`\\usepackage${options}{${item.name}}`);
  }
  return { source: `${lines.join("\n")}\n`, warnings, preserve };
}

function replaceManagedSection(
  source: string,
  section: keyof typeof MANAGED_MARKERS,
  replacement: string
): { source: string; replaced: boolean } {
  const beginMarker = MANAGED_MARKERS[section].begin;
  const endMarker = MANAGED_MARKERS[section].end;
  const begin = source.indexOf(beginMarker);
  const end = source.indexOf(endMarker);
  if (begin < 0 && end < 0) return { source, replaced: false };
  if (begin < 0 || end < 0 || end <= begin) {
    throw new ProfileRuntimeError(`The managed ${section} markers are incomplete or out of order.`, "MARKERS_INVALID");
  }
  const beginLineEnd = source.indexOf("\n", begin + beginMarker.length);
  if (beginLineEnd < 0 || beginLineEnd >= end) {
    throw new ProfileRuntimeError(`The managed ${section} block has no writable body.`, "MARKERS_INVALID");
  }
  const newline = source.includes("\r\n") ? "\r\n" : "\n";
  return {
    source: `${source.slice(0, beginLineEnd + 1)}${replacement.replace(/\n/g, newline)}${source.slice(end)}`,
    replaced: true
  };
}

export function renderProfileStructure(
  target: DocumentTarget,
  profile: BuildProfile,
  focusOverride?: string[]
): string {
  const focusNodes = focusOverride?.length ? focusOverride : profile.focusNodes;
  const focused = focusNodes?.length ? new Set(focusNodes) : null;
  const lines: string[] = ["% Generated by LaTeX Workbench. Do not edit."];

  for (const node of orderedNodes(target, profile)) {
    if (!nodeEnabled(node, profile)) continue;
    const isChapterLike = node.kind === "chapter" || node.kind === "input";
    const state = isChapterLike
      ? (focused && !focused.has(node.id) ? "hidden" : profile.chapterState[node.id] ?? "full")
      : "full";
    if (state === "hidden") continue;

    lines.push(`% node:${node.id} state:${state}`);
    if (profile.numbering === "preserve" && isChapterLike && node.phase !== "appendix" && node.originalNumber && node.originalNumber > 0) {
      lines.push(`\\LWPreserveChapter{${Math.trunc(node.originalNumber)}}`);
    }
    lines.push(state === "titleOnly" ? titleOnlySource(node) : sourceForNode(node));
  }
  return `${lines.join("\n")}\n`;
}

function replaceManagedStructure(source: string, renderedStructure: string): { source: string; replaced: boolean } {
  return replaceManagedSection(source, "structure", renderedStructure);
}

function runtimeSource(profile: BuildProfile): string {
  const profileName = profile.name.replace(/[\r\n]/g, " ");
  return [
    "% Generated by LaTeX Workbench. Do not edit.",
    `\\def\\LWProfileId{${escapeTexText(profile.id)}}`,
    `\\def\\LWProfileName{${escapeTexText(profileName)}}`,
    profile.numbering === "preserve"
      ? "\\providecommand{\\LWPreserveChapter}[1]{\\setcounter{chapter}{\\numexpr#1-1\\relax}}"
      : "\\providecommand{\\LWPreserveChapter}[1]{}",
    ""
  ].join("\n");
}

function injectRuntime(source: string, runtimeFileName: string): string {
  const documentClass = /(^|\n)([ \t]*\\documentclass(?:\[[^\]]*\])?\s*\{[^}]+\}[^\r\n]*)/.exec(source);
  if (!documentClass || documentClass.index === undefined) {
    throw new ProfileRuntimeError("The entry file does not contain an active \\documentclass declaration.", "ENTRY_INVALID");
  }
  const insertion = documentClass.index + documentClass[0].length;
  const newline = source.includes("\r\n") ? "\r\n" : "\n";
  return `${source.slice(0, insertion)}${newline}\\input{${texPath(runtimeFileName)}}${source.slice(insertion)}`;
}

export async function createProfileRuntime(
  projectRoot: string,
  target: DocumentTarget,
  profile: BuildProfile,
  options: ProfileRuntimeOptions = {}
): Promise<ProfileRuntimeResult> {
  const absoluteRoot = await realpath(resolve(projectRoot));
  const originalEntryPath = await resolveInside(absoluteRoot, target.entry);
  const source = await readFile(originalEntryPath, "utf8");
  const buildDirectory = await ensureBuildDirectory(absoluteRoot, target.id, profile.id);

  const runtimeFileName = "latex-workbench-runtime.tex";
  const generatedEntryFileName = `latex-workbench-entry${extname(originalEntryPath) || ".tex"}`;
  const wrapperFileName = "latex-workbench-wrapper.tex";
  const latexmkrcFileName = ".latexmkrc";
  const runtimePath = join(buildDirectory, runtimeFileName);
  const generatedEntryPath = join(buildDirectory, generatedEntryFileName);
  const wrapperPath = join(buildDirectory, wrapperFileName);
  const latexmkrcPath = join(buildDirectory, latexmkrcFileName);
  const runtimeTarget = targetWithPreservedInputCommands(source, absoluteRoot, originalEntryPath, target);
  const renderedStructure = renderProfileStructure(runtimeTarget, profile, options.focusNodes);
  const packageResult = profile.enabledBlocks.packages !== false
    ? renderManagedPackages(runtimeTarget, profile)
    : { source: "% Packages disabled for this profile.\n", warnings: [] as string[], preserve: false };
  let transformedSource = source;
  const warnings = [...packageResult.warnings];
  if (profile.enabledBlocks.class !== false) {
    const classResult = replaceManagedSection(transformedSource, "class", renderClassDeclaration(runtimeTarget));
    transformedSource = classResult.source;
    if (!classResult.replaced) warnings.push("Managed class markers were not found; class configuration is compiled unchanged.");
  }
  if (profile.enabledBlocks.packages !== false && !packageResult.preserve) {
    const packagesResult = replaceManagedSection(transformedSource, "packages", packageResult.source);
    transformedSource = packagesResult.source;
    if (!packagesResult.replaced) warnings.push("Managed package markers were not found; package configuration is compiled unchanged.");
  } else {
    const packagesResult = replaceManagedSection(transformedSource, "packages", "% Packages disabled for this profile.\n");
    transformedSource = packagesResult.source;
  }
  if (profile.enabledBlocks.structure !== false) {
    const transformed = replaceManagedStructure(transformedSource, renderedStructure);
    transformedSource = transformed.source;
    if (!transformed.replaced) warnings.push("Managed structure markers were not found; the original structure is compiled unchanged.");
  }
  const generatedEntry = injectRuntime(transformedSource, runtimeFileName);
  for (const directory of includeAuxiliaryDirectories(generatedEntry, warnings)) {
    await ensureBuildSubdirectory(buildDirectory, directory);
  }
  const texSearchRoots = [...new Set([dirname(originalEntryPath), absoluteRoot])]
    .map((path) => `{${texPath(path).replace(/\/$/, "")}/}`)
    .join("");
  const wrapperEngine = options.engine ?? (target.engine === "auto" ? undefined : target.engine);
  const wrapper = [
    "% Generated by LaTeX Workbench. Do not edit.",
    ...(wrapperEngine ? [`% !TEX program = ${wrapperEngine}`] : []),
    "% Open this file in VS Code to compile the selected Workbench profile.",
    "\\makeatletter",
    `\\def\\input@path{${texSearchRoots}}`,
    "\\makeatother",
    `\\input{${texPath(basename(generatedEntryPath))}}`,
    ""
  ].join("\n");

  await Promise.all([
    writeGeneratedFile(runtimePath, runtimeSource(profile)),
    writeGeneratedFile(generatedEntryPath, generatedEntry),
    writeGeneratedFile(wrapperPath, wrapper),
    writeGeneratedFile(latexmkrcPath, renderLatexmkrc(absoluteRoot, dirname(originalEntryPath), buildDirectory))
  ]);

  return {
    buildDirectory,
    runtimePath,
    wrapperPath,
    latexmkrcPath,
    generatedEntryPath,
    originalEntryPath,
    renderedStructure,
    warnings
  };
}

export const generateProfileRuntime = createProfileRuntime;
export const generateRuntime = createProfileRuntime;
